# Generated by Django 5.2.4 on 2025-07-23 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of Department')),
                ('abbreviation', models.CharField(blank=True, max_length=50, verbose_name='Abbreviation of Department')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the department is currently active.', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.department', verbose_name='Department'),
        ),
    ]
