# Generated by Django 5.2.4 on 2025-07-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_department_user_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Órgão/Unidade', 'verbose_name_plural': 'Órgãos/Unidades'},
        ),
        migrations.AddField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False, verbose_name='Forçar troca de senha no próximo login'),
        ),
        migrations.AlterField(
            model_name='department',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome'),
        ),
    ]
